### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by iLoveTux** [argaen/python-google-distance-matrix#1]
After searching for a solution to accessing google distance matrix api from python I came across your repository. The code looks good and I would love to commit some of my time to help. I  see that you had wanted to add the ability to use an api key, and as that is functionality I would have to add anyway I would be willing to write it into your library.

The only issue I have is that I don't see the license type indicated and I would like to know beforehand if I can use this in my commercial product.

**Comment by argaen** [comment]
I've just added gplv3 license. You can check info about licenses at [choosealicense](http://choosealicense.com/licenses/) in case you need it. Contributions will be welcome!

**Comment by iLoveTux** [comment]
Thank you so much. I have already forked and will have the patch in the next couple of days.

Thank you for the work you've done already and also for the quick response. In my opinion this issue should be closed.
