### ISSUE TITLE
Would you mind adding 'timeout' feature?

### ISSUE THREAD

**Issue by gzeronet** [argaen/python-google-distance-matrix#2]
Hi argaen,

The package helped me a lot.

If possible, could you please add a param 'timeout' in function 'make_request'. I have to wait until the URL timeout if some address not valid now.

Thanks.

**Comment by argaen** [comment]
Hi gzeronet, glad it is useful to you.

I think I don't understand when you say 'address not valid now'. The make_request function only calls the DISTANCE_MATRIX_URL which is the Googles API using the destinations and origins you have set.

Can you provide a sample code which triggers the timeout so I can test it and understand it? ^^

**Comment by gzeronet** [comment]
Hi argaen,

Sorry for my incorrect description on the issue, I've realized the problem is on my network (because of the G_F_W in China :-1:  ). You are right, google api will return response immediately whatever the address is. So, I still wish the param 'timeout' could be added for some network issues.

Please let me know if you need some other info about this feature request, or a patch file I can provide.
Thanks again.

**Comment by argaen** [comment]
All right, now I understand it. Yes, I will check today when I have some time.

**Comment by gzeronet** [comment]
:+1:

**Comment by argaen** [comment]
Set timeout=5, if it timeouts, the function returns False.
Sorry for the delay =/.  
3ed21817c8cfba8d29809c1878d453c04dff09bb

**Comment by gzeronet** [comment]
Hey, never mind ;-) . 
Hmm, i feel it is no need to handle the exceptions in your package. I can catch the URLError (with some error msg) on my code when make_request. 
Unfortunately, im away from my PC about one week, i will reply you late with my patch file. Thx.

**Comment by argaen** [comment]
Yup right, I've moved the try/except to the test.py file. This code is about requesting data to google distance matrix so I'll let others deal with exceptions as u've said ;). ty!

**Comment by gzeronet** [comment]
Not sure how to push my code, just paste my patch here:

```
diff --git a/google_distance_matrix/core.py b/google_distance_matrix/core.py
index 6df2aa9..c361f0f 100644
--- a/google_distance_matrix/core.py
+++ b/google_distance_matrix/core.py
@@ -45,7 +45,7 @@ class DM(object):
         self.origins = ''
         self.destinations = ''

-    def make_request(self, origins, destinations, mode='driving'):
+    def make_request(self, origins, destinations, mode='driving', timeout=None):
         data = {}
         self.origins = [origins] if type(origins) == str else origins
         self.destinations = [destinations] if type(destinations) == str else destinations
@@ -59,7 +59,7 @@ class DM(object):
         url = os.path.join(self.url, output_format)

         # print ast.literal_eval(urllib2.urlopen(url + '?' + url_values).read())
-        self.response = ast.literal_eval(urllib2.urlopen(url + '?' + url_values, timeout=5).read())['rows']
+        self.response = ast.literal_eval(urllib2.urlopen(url + '?' + url_values, timeout=timeout).read())['rows']
         self.dict_response = {'distance': {'value': {}, 'text': {}, },  # Reset temporary dict
                               'duration': {'value': {}, 'text': {}, },
                               }
```

I wish the value of 'timeout' could be passed, not hard code. Could you patch it ? I've tested, no problem.
Thanks, man. :-)

**Comment by gzeronet** [comment]
Hmm..., please let me know if something unreasonable.

**Comment by argaen** [comment]
FYI, for larger modifications it's better to use [pull requests](https://help.github.com/articles/using-pull-requests). Ofc, for this small modifications it's allright providing the patch ;). Ty

**Comment by gzeronet** [comment]
Perfect, thx for sharing and could you update the package for pip install also? ;)

**Comment by argaen** [comment]
Done ;)

**Comment by gzeronet** [comment]
Appreciate that, man. Continue on my work.
